buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // En az 7.0 veya üzeri bir sürüm olduğundan emin olun
        classpath 'com.android.tools.build:gradle:8.3.2' 
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
