buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Gradle 8.7 ile tam uyumlu Android Plugin sürümü
        classpath 'com.android.tools.build:gradle:8.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"
    }
}

// Depo tanımları settings.gradle içinde olduğu için burası boş bırakıldı
